version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: gh-pr-feedback
    main: ./main.go
    binary: gh-pr-feedback
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: gh-pr-feedback
    format: tar.gz
    # Use .exe extension for Windows
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

release:
  github:
    owner: lachlanc
    name: gh-pr-feedback
  name_template: "v{{.Version}}"
  header: |
    ## What's Changed
    
    {{ .TagBody }}
    
    ## Installation
    
    Install via GitHub CLI:
    ```bash
    gh extension install lachlanc/gh-pr-feedback
    ```
    
    Or download the binary for your platform below.

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'